DROP TABLE IF EXISTS chat;
DROP TABLE IF EXISTS privateChat;

CREATE TABLE chat(
    id SERIAL PRIMARY KEY,
    message VARCHAR(1000) NOT NULL,
    userId INT NOT NULL REFERENCES users(id),
    ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE privateChat(
    id SERIAL PRIMARY KEY,
    message VARCHAR(1000) NOT NULL,
    userId INT NOT NULL REFERENCES users(id),
    friendId INT NOT NULL,
    ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
